### ISSUE TITLE
Expanding snippert doesn't work

### ISSUE THREAD

**Issue by osleg** [roxma/nvim-completion-manager#135] opened 2017-09-13 09:57 UTC
In my vimrc I have <C-j> to expand ultisnip
```
      let g:UltiSnipsExpandTrigger = '<C-j>'
```
So I added the mappings as advised on help
```
imap <expr> <CR>  (pumvisible() ?  "\<c-y>\<Plug>(expand_or_nl)" : "\<CR>")
imap <expr> <Plug>(expand_or_nl) (cm#completed_is_snippet() ? "\<C-j>":"\<CR>")
```
Tho instead of triggering the snippet I'm getting `<Plug>(expand_or_nl)` printed out

**Comment by roxma** [comment] 2017-09-14 01:42
I'll need your minimal vimrc and reproducing steps to reproduce this issue.

**Comment by roxma** [comment] 2017-09-14 01:45
This issue may have useful information: https://github.com/roxma/nvim-completion-manager/issues/89#issuecomment-309207317

**Comment by osleg** [comment] 2017-09-18 12:49
I used this as super minimal vimrc
```
call plug#begin('~/.vim/plugged')

Plug 'roxma/nvim-completion-manager'
Plug 'jmcantrell/vim-virtualenv', has('gui') ? {'for': ['python']} : {}
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

call plug#end()
imap <expr> <CR>  (pumvisible() ?  "\<c-y>\<Plug>(expand_or_nl)" : "\<CR>")
imap <expr> <Plug>(expand_or_nl) (cm#completed_is_snippet() ? "\<C-j>":"\<CR>")
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

let g:UltiSnipsExpandTrigger = '<C-j>'
let g:UltiSnipsJumpForwardTrigger = '<C-j>'
let g:UltiSnipsJumpBackwardTrigger = '<C-k>'
let g:UltiSnipsListSnippets="<c-s-j>"
```
And it worked, so I guess the problem is somewhere in the config file, any idea how to debug this except of commenting most of config and adding stuff line by line?

**Comment by roxma** [comment] 2017-09-19 01:09
Maybe there's mapping collision on the `<CR>` key among your plugins.

**Comment by roxma** [comment] 2017-09-19 01:11
I'm closing this issue, since this is not NCM issue.

Feel free to continue the discussion.

**Closed by roxma** 2017-09-19 01:11 UTC

**Comment by qazip** [comment] 2018-03-04 11:27
@osleg , did you find out what was the culprif of `<Plug>(expand_or_nl)`? I'm having exactly the same problem..

**Comment by osleg** [comment] 2018-03-04 11:36
Unfortunately no, I just reverted to using <C-j> for snippets expansion.
