### ISSUE TITLE
File path is not relative to file

### ISSUE THREAD

**Issue by ggsalas** [roxma/nvim-completion-manager#68] opened 2017-04-18 22:10 UTC
Hi, I have noted that the autocomplete path is not showing options relative to the current directory of the editted file. Have missed some configuration? 

Regards,

**Comment by roxma** [comment] 2017-04-19 01:09
There is completion relative to current file, how do you reproduce the issue?

**Comment by roxma** [comment] 2017-04-20 06:36
I'm closing this due to the lack of detail.

**Closed by roxma** 2017-04-20 06:36 UTC
